mkdir Em10_Fala1_CarolinaHolly, Em10_Fala1_CarolinaHolly\images, Em10_Fala1_CarolinaHolly\audio, Em10_Fala1_CarolinaHolly\video, Em10_Fala1_CarolinaHolly\keypoints
move Em10_Fala1_CarolinaHolly.mp4, Em10_Fala1_CarolinaHolly\video\Em10_Fala1_CarolinaHolly.mp4
mkdir Em10_Fala1_Neutra_CarolinaHolly, Em10_Fala1_Neutra_CarolinaHolly\images, Em10_Fala1_Neutra_CarolinaHolly\audio, Em10_Fala1_Neutra_CarolinaHolly\video, Em10_Fala1_Neutra_CarolinaHolly\keypoints
move Em10_Fala1_Neutra_CarolinaHolly.mp4, Em10_Fala1_Neutra_CarolinaHolly\video\Em10_Fala1_Neutra_CarolinaHolly.mp4
mkdir Em10_Fala2_CarolinaHolly, Em10_Fala2_CarolinaHolly\images, Em10_Fala2_CarolinaHolly\audio, Em10_Fala2_CarolinaHolly\video, Em10_Fala2_CarolinaHolly\keypoints
move Em10_Fala2_CarolinaHolly.mp4, Em10_Fala2_CarolinaHolly\video\Em10_Fala2_CarolinaHolly.mp4
mkdir Em10_Fala2_Neutra_CarolinaHolly, Em10_Fala2_Neutra_CarolinaHolly\images, Em10_Fala2_Neutra_CarolinaHolly\audio, Em10_Fala2_Neutra_CarolinaHolly\video, Em10_Fala2_Neutra_CarolinaHolly\keypoints
move Em10_Fala2_Neutra_CarolinaHolly.mp4, Em10_Fala2_Neutra_CarolinaHolly\video\Em10_Fala2_Neutra_CarolinaHolly.mp4
mkdir Em10_Fala3_CarolinaHolly, Em10_Fala3_CarolinaHolly\images, Em10_Fala3_CarolinaHolly\audio, Em10_Fala3_CarolinaHolly\video, Em10_Fala3_CarolinaHolly\keypoints
move Em10_Fala3_CarolinaHolly.mp4, Em10_Fala3_CarolinaHolly\video\Em10_Fala3_CarolinaHolly.mp4
mkdir Em10_Fala3_Neutra_CarolinaHolly, Em10_Fala3_Neutra_CarolinaHolly\images, Em10_Fala3_Neutra_CarolinaHolly\audio, Em10_Fala3_Neutra_CarolinaHolly\video, Em10_Fala3_Neutra_CarolinaHolly\keypoints
move Em10_Fala3_Neutra_CarolinaHolly.mp4, Em10_Fala3_Neutra_CarolinaHolly\video\Em10_Fala3_Neutra_CarolinaHolly.mp4
mkdir Em11_Fala1_CarolinaHolly, Em11_Fala1_CarolinaHolly\images, Em11_Fala1_CarolinaHolly\audio, Em11_Fala1_CarolinaHolly\video, Em11_Fala1_CarolinaHolly\keypoints
move Em11_Fala1_CarolinaHolly.mp4, Em11_Fala1_CarolinaHolly\video\Em11_Fala1_CarolinaHolly.mp4
mkdir Em11_Fala1_Neutra_CarolinaHolly, Em11_Fala1_Neutra_CarolinaHolly\images, Em11_Fala1_Neutra_CarolinaHolly\audio, Em11_Fala1_Neutra_CarolinaHolly\video, Em11_Fala1_Neutra_CarolinaHolly\keypoints
move Em11_Fala1_Neutra_CarolinaHolly.mp4, Em11_Fala1_Neutra_CarolinaHolly\video\Em11_Fala1_Neutra_CarolinaHolly.mp4
mkdir Em11_Fala2_CarolinaHolly, Em11_Fala2_CarolinaHolly\images, Em11_Fala2_CarolinaHolly\audio, Em11_Fala2_CarolinaHolly\video, Em11_Fala2_CarolinaHolly\keypoints
move Em11_Fala2_CarolinaHolly.mp4, Em11_Fala2_CarolinaHolly\video\Em11_Fala2_CarolinaHolly.mp4
mkdir Em11_Fala2_Neutra_CarolinaHolly, Em11_Fala2_Neutra_CarolinaHolly\images, Em11_Fala2_Neutra_CarolinaHolly\audio, Em11_Fala2_Neutra_CarolinaHolly\video, Em11_Fala2_Neutra_CarolinaHolly\keypoints
move Em11_Fala2_Neutra_CarolinaHolly.mp4, Em11_Fala2_Neutra_CarolinaHolly\video\Em11_Fala2_Neutra_CarolinaHolly.mp4
mkdir Em11_Fala3_CarolinaHolly, Em11_Fala3_CarolinaHolly\images, Em11_Fala3_CarolinaHolly\audio, Em11_Fala3_CarolinaHolly\video, Em11_Fala3_CarolinaHolly\keypoints
move Em11_Fala3_CarolinaHolly.mp4, Em11_Fala3_CarolinaHolly\video\Em11_Fala3_CarolinaHolly.mp4
mkdir Em11_Fala3_Neutra_CarolinaHolly, Em11_Fala3_Neutra_CarolinaHolly\images, Em11_Fala3_Neutra_CarolinaHolly\audio, Em11_Fala3_Neutra_CarolinaHolly\video, Em11_Fala3_Neutra_CarolinaHolly\keypoints
move Em11_Fala3_Neutra_CarolinaHolly.mp4, Em11_Fala3_Neutra_CarolinaHolly\video\Em11_Fala3_Neutra_CarolinaHolly.mp4
mkdir Em12_Fala1_CarolinaHolly, Em12_Fala1_CarolinaHolly\images, Em12_Fala1_CarolinaHolly\audio, Em12_Fala1_CarolinaHolly\video, Em12_Fala1_CarolinaHolly\keypoints
move Em12_Fala1_CarolinaHolly.mp4, Em12_Fala1_CarolinaHolly\video\Em12_Fala1_CarolinaHolly.mp4
mkdir Em12_Fala1_Neutra_CarolinaHolly, Em12_Fala1_Neutra_CarolinaHolly\images, Em12_Fala1_Neutra_CarolinaHolly\audio, Em12_Fala1_Neutra_CarolinaHolly\video, Em12_Fala1_Neutra_CarolinaHolly\keypoints
move Em12_Fala1_Neutra_CarolinaHolly.mp4, Em12_Fala1_Neutra_CarolinaHolly\video\Em12_Fala1_Neutra_CarolinaHolly.mp4
mkdir Em12_Fala2_CarolinaHolly, Em12_Fala2_CarolinaHolly\images, Em12_Fala2_CarolinaHolly\audio, Em12_Fala2_CarolinaHolly\video, Em12_Fala2_CarolinaHolly\keypoints
move Em12_Fala2_CarolinaHolly.mp4, Em12_Fala2_CarolinaHolly\video\Em12_Fala2_CarolinaHolly.mp4
mkdir Em12_Fala2_Neutra_CarolinaHolly, Em12_Fala2_Neutra_CarolinaHolly\images, Em12_Fala2_Neutra_CarolinaHolly\audio, Em12_Fala2_Neutra_CarolinaHolly\video, Em12_Fala2_Neutra_CarolinaHolly\keypoints
move Em12_Fala2_Neutra_CarolinaHolly.mp4, Em12_Fala2_Neutra_CarolinaHolly\video\Em12_Fala2_Neutra_CarolinaHolly.mp4
mkdir Em12_Fala3_CarolinaHolly, Em12_Fala3_CarolinaHolly\images, Em12_Fala3_CarolinaHolly\audio, Em12_Fala3_CarolinaHolly\video, Em12_Fala3_CarolinaHolly\keypoints
move Em12_Fala3_CarolinaHolly.mp4, Em12_Fala3_CarolinaHolly\video\Em12_Fala3_CarolinaHolly.mp4
mkdir Em12_Fala3_Neutra_CarolinaHolly, Em12_Fala3_Neutra_CarolinaHolly\images, Em12_Fala3_Neutra_CarolinaHolly\audio, Em12_Fala3_Neutra_CarolinaHolly\video, Em12_Fala3_Neutra_CarolinaHolly\keypoints
move Em12_Fala3_Neutra_CarolinaHolly.mp4, Em12_Fala3_Neutra_CarolinaHolly\video\Em12_Fala3_Neutra_CarolinaHolly.mp4
mkdir Em13_Fala1_CarolinaHolly, Em13_Fala1_CarolinaHolly\images, Em13_Fala1_CarolinaHolly\audio, Em13_Fala1_CarolinaHolly\video, Em13_Fala1_CarolinaHolly\keypoints
move Em13_Fala1_CarolinaHolly.mp4, Em13_Fala1_CarolinaHolly\video\Em13_Fala1_CarolinaHolly.mp4
mkdir Em13_Fala1_Neutra_CarolinaHolly, Em13_Fala1_Neutra_CarolinaHolly\images, Em13_Fala1_Neutra_CarolinaHolly\audio, Em13_Fala1_Neutra_CarolinaHolly\video, Em13_Fala1_Neutra_CarolinaHolly\keypoints
move Em13_Fala1_Neutra_CarolinaHolly.mp4, Em13_Fala1_Neutra_CarolinaHolly\video\Em13_Fala1_Neutra_CarolinaHolly.mp4
mkdir Em13_Fala2_CarolinaHolly, Em13_Fala2_CarolinaHolly\images, Em13_Fala2_CarolinaHolly\audio, Em13_Fala2_CarolinaHolly\video, Em13_Fala2_CarolinaHolly\keypoints
move Em13_Fala2_CarolinaHolly.mp4, Em13_Fala2_CarolinaHolly\video\Em13_Fala2_CarolinaHolly.mp4
mkdir Em13_Fala2_Neutra_CarolinaHolly, Em13_Fala2_Neutra_CarolinaHolly\images, Em13_Fala2_Neutra_CarolinaHolly\audio, Em13_Fala2_Neutra_CarolinaHolly\video, Em13_Fala2_Neutra_CarolinaHolly\keypoints
move Em13_Fala2_Neutra_CarolinaHolly.mp4, Em13_Fala2_Neutra_CarolinaHolly\video\Em13_Fala2_Neutra_CarolinaHolly.mp4
mkdir Em13_Fala3_CarolinaHolly, Em13_Fala3_CarolinaHolly\images, Em13_Fala3_CarolinaHolly\audio, Em13_Fala3_CarolinaHolly\video, Em13_Fala3_CarolinaHolly\keypoints
move Em13_Fala3_CarolinaHolly.mp4, Em13_Fala3_CarolinaHolly\video\Em13_Fala3_CarolinaHolly.mp4
mkdir Em13_Fala3_Neutra_CarolinaHolly, Em13_Fala3_Neutra_CarolinaHolly\images, Em13_Fala3_Neutra_CarolinaHolly\audio, Em13_Fala3_Neutra_CarolinaHolly\video, Em13_Fala3_Neutra_CarolinaHolly\keypoints
move Em13_Fala3_Neutra_CarolinaHolly.mp4, Em13_Fala3_Neutra_CarolinaHolly\video\Em13_Fala3_Neutra_CarolinaHolly.mp4
mkdir Em14_Fala1_CarolinaHolly, Em14_Fala1_CarolinaHolly\images, Em14_Fala1_CarolinaHolly\audio, Em14_Fala1_CarolinaHolly\video, Em14_Fala1_CarolinaHolly\keypoints
move Em14_Fala1_CarolinaHolly.mp4, Em14_Fala1_CarolinaHolly\video\Em14_Fala1_CarolinaHolly.mp4
mkdir Em14_Fala1_Neutra_CarolinaHolly, Em14_Fala1_Neutra_CarolinaHolly\images, Em14_Fala1_Neutra_CarolinaHolly\audio, Em14_Fala1_Neutra_CarolinaHolly\video, Em14_Fala1_Neutra_CarolinaHolly\keypoints
move Em14_Fala1_Neutra_CarolinaHolly.mp4, Em14_Fala1_Neutra_CarolinaHolly\video\Em14_Fala1_Neutra_CarolinaHolly.mp4
mkdir Em14_Fala2_CarolinaHolly, Em14_Fala2_CarolinaHolly\images, Em14_Fala2_CarolinaHolly\audio, Em14_Fala2_CarolinaHolly\video, Em14_Fala2_CarolinaHolly\keypoints
move Em14_Fala2_CarolinaHolly.mp4, Em14_Fala2_CarolinaHolly\video\Em14_Fala2_CarolinaHolly.mp4
mkdir Em14_Fala2_Neutra_CarolinaHolly, Em14_Fala2_Neutra_CarolinaHolly\images, Em14_Fala2_Neutra_CarolinaHolly\audio, Em14_Fala2_Neutra_CarolinaHolly\video, Em14_Fala2_Neutra_CarolinaHolly\keypoints
move Em14_Fala2_Neutra_CarolinaHolly.mp4, Em14_Fala2_Neutra_CarolinaHolly\video\Em14_Fala2_Neutra_CarolinaHolly.mp4
mkdir Em15_Fala1_CarolinaHolly, Em15_Fala1_CarolinaHolly\images, Em15_Fala1_CarolinaHolly\audio, Em15_Fala1_CarolinaHolly\video, Em15_Fala1_CarolinaHolly\keypoints
move Em15_Fala1_CarolinaHolly.mp4, Em15_Fala1_CarolinaHolly\video\Em15_Fala1_CarolinaHolly.mp4
mkdir Em15_Fala1_Neutra_CarolinaHolly, Em15_Fala1_Neutra_CarolinaHolly\images, Em15_Fala1_Neutra_CarolinaHolly\audio, Em15_Fala1_Neutra_CarolinaHolly\video, Em15_Fala1_Neutra_CarolinaHolly\keypoints
move Em15_Fala1_Neutra_CarolinaHolly.mp4, Em15_Fala1_Neutra_CarolinaHolly\video\Em15_Fala1_Neutra_CarolinaHolly.mp4
mkdir Em15_Fala2_CarolinaHolly, Em15_Fala2_CarolinaHolly\images, Em15_Fala2_CarolinaHolly\audio, Em15_Fala2_CarolinaHolly\video, Em15_Fala2_CarolinaHolly\keypoints
move Em15_Fala2_CarolinaHolly.mp4, Em15_Fala2_CarolinaHolly\video\Em15_Fala2_CarolinaHolly.mp4
mkdir Em15_Fala2_Neutra_CarolinaHolly, Em15_Fala2_Neutra_CarolinaHolly\images, Em15_Fala2_Neutra_CarolinaHolly\audio, Em15_Fala2_Neutra_CarolinaHolly\video, Em15_Fala2_Neutra_CarolinaHolly\keypoints
move Em15_Fala2_Neutra_CarolinaHolly.mp4, Em15_Fala2_Neutra_CarolinaHolly\video\Em15_Fala2_Neutra_CarolinaHolly.mp4
mkdir Em15_Fala3_CarolinaHolly, Em15_Fala3_CarolinaHolly\images, Em15_Fala3_CarolinaHolly\audio, Em15_Fala3_CarolinaHolly\video, Em15_Fala3_CarolinaHolly\keypoints
move Em15_Fala3_CarolinaHolly.mp4, Em15_Fala3_CarolinaHolly\video\Em15_Fala3_CarolinaHolly.mp4
mkdir Em15_Fala3_Neutra_CarolinaHolly, Em15_Fala3_Neutra_CarolinaHolly\images, Em15_Fala3_Neutra_CarolinaHolly\audio, Em15_Fala3_Neutra_CarolinaHolly\video, Em15_Fala3_Neutra_CarolinaHolly\keypoints
move Em15_Fala3_Neutra_CarolinaHolly.mp4, Em15_Fala3_Neutra_CarolinaHolly\video\Em15_Fala3_Neutra_CarolinaHolly.mp4
mkdir Em16_Fala1_CarolinaHolly, Em16_Fala1_CarolinaHolly\images, Em16_Fala1_CarolinaHolly\audio, Em16_Fala1_CarolinaHolly\video, Em16_Fala1_CarolinaHolly\keypoints
move Em16_Fala1_CarolinaHolly.mp4, Em16_Fala1_CarolinaHolly\video\Em16_Fala1_CarolinaHolly.mp4
mkdir Em16_Fala1_Neutra_CarolinaHolly, Em16_Fala1_Neutra_CarolinaHolly\images, Em16_Fala1_Neutra_CarolinaHolly\audio, Em16_Fala1_Neutra_CarolinaHolly\video, Em16_Fala1_Neutra_CarolinaHolly\keypoints
move Em16_Fala1_Neutra_CarolinaHolly.mp4, Em16_Fala1_Neutra_CarolinaHolly\video\Em16_Fala1_Neutra_CarolinaHolly.mp4
mkdir Em16_Fala2_CarolinaHolly, Em16_Fala2_CarolinaHolly\images, Em16_Fala2_CarolinaHolly\audio, Em16_Fala2_CarolinaHolly\video, Em16_Fala2_CarolinaHolly\keypoints
move Em16_Fala2_CarolinaHolly.mp4, Em16_Fala2_CarolinaHolly\video\Em16_Fala2_CarolinaHolly.mp4
mkdir Em16_Fala2_Neutra_CarolinaHolly, Em16_Fala2_Neutra_CarolinaHolly\images, Em16_Fala2_Neutra_CarolinaHolly\audio, Em16_Fala2_Neutra_CarolinaHolly\video, Em16_Fala2_Neutra_CarolinaHolly\keypoints
move Em16_Fala2_Neutra_CarolinaHolly.mp4, Em16_Fala2_Neutra_CarolinaHolly\video\Em16_Fala2_Neutra_CarolinaHolly.mp4
mkdir Em16_Fala3_CarolinaHolly, Em16_Fala3_CarolinaHolly\images, Em16_Fala3_CarolinaHolly\audio, Em16_Fala3_CarolinaHolly\video, Em16_Fala3_CarolinaHolly\keypoints
move Em16_Fala3_CarolinaHolly.mp4, Em16_Fala3_CarolinaHolly\video\Em16_Fala3_CarolinaHolly.mp4
mkdir Em16_Fala3_Neutra_CarolinaHolly, Em16_Fala3_Neutra_CarolinaHolly\images, Em16_Fala3_Neutra_CarolinaHolly\audio, Em16_Fala3_Neutra_CarolinaHolly\video, Em16_Fala3_Neutra_CarolinaHolly\keypoints
move Em16_Fala3_Neutra_CarolinaHolly.mp4, Em16_Fala3_Neutra_CarolinaHolly\video\Em16_Fala3_Neutra_CarolinaHolly.mp4
mkdir Em17_Fala1_CarolinaHolly, Em17_Fala1_CarolinaHolly\images, Em17_Fala1_CarolinaHolly\audio, Em17_Fala1_CarolinaHolly\video, Em17_Fala1_CarolinaHolly\keypoints
move Em17_Fala1_CarolinaHolly.mp4, Em17_Fala1_CarolinaHolly\video\Em17_Fala1_CarolinaHolly.mp4
mkdir Em17_Fala1_Neutra_CarolinaHolly, Em17_Fala1_Neutra_CarolinaHolly\images, Em17_Fala1_Neutra_CarolinaHolly\audio, Em17_Fala1_Neutra_CarolinaHolly\video, Em17_Fala1_Neutra_CarolinaHolly\keypoints
move Em17_Fala1_Neutra_CarolinaHolly.mp4, Em17_Fala1_Neutra_CarolinaHolly\video\Em17_Fala1_Neutra_CarolinaHolly.mp4
mkdir Em17_Fala2_CarolinaHolly, Em17_Fala2_CarolinaHolly\images, Em17_Fala2_CarolinaHolly\audio, Em17_Fala2_CarolinaHolly\video, Em17_Fala2_CarolinaHolly\keypoints
move Em17_Fala2_CarolinaHolly.mp4, Em17_Fala2_CarolinaHolly\video\Em17_Fala2_CarolinaHolly.mp4
mkdir Em17_Fala2_Neutra_CarolinaHolly, Em17_Fala2_Neutra_CarolinaHolly\images, Em17_Fala2_Neutra_CarolinaHolly\audio, Em17_Fala2_Neutra_CarolinaHolly\video, Em17_Fala2_Neutra_CarolinaHolly\keypoints
move Em17_Fala2_Neutra_CarolinaHolly.mp4, Em17_Fala2_Neutra_CarolinaHolly\video\Em17_Fala2_Neutra_CarolinaHolly.mp4
mkdir Em17_Fala3_CarolinaHolly, Em17_Fala3_CarolinaHolly\images, Em17_Fala3_CarolinaHolly\audio, Em17_Fala3_CarolinaHolly\video, Em17_Fala3_CarolinaHolly\keypoints
move Em17_Fala3_CarolinaHolly.mp4, Em17_Fala3_CarolinaHolly\video\Em17_Fala3_CarolinaHolly.mp4
mkdir Em17_Fala3_Neutra_CarolinaHolly, Em17_Fala3_Neutra_CarolinaHolly\images, Em17_Fala3_Neutra_CarolinaHolly\audio, Em17_Fala3_Neutra_CarolinaHolly\video, Em17_Fala3_Neutra_CarolinaHolly\keypoints
move Em17_Fala3_Neutra_CarolinaHolly.mp4, Em17_Fala3_Neutra_CarolinaHolly\video\Em17_Fala3_Neutra_CarolinaHolly.mp4
mkdir Em18_Fala1_CarolinaHolly, Em18_Fala1_CarolinaHolly\images, Em18_Fala1_CarolinaHolly\audio, Em18_Fala1_CarolinaHolly\video, Em18_Fala1_CarolinaHolly\keypoints
move Em18_Fala1_CarolinaHolly.mp4, Em18_Fala1_CarolinaHolly\video\Em18_Fala1_CarolinaHolly.mp4
mkdir Em18_Fala1_Neutra_CarolinaHolly, Em18_Fala1_Neutra_CarolinaHolly\images, Em18_Fala1_Neutra_CarolinaHolly\audio, Em18_Fala1_Neutra_CarolinaHolly\video, Em18_Fala1_Neutra_CarolinaHolly\keypoints
move Em18_Fala1_Neutra_CarolinaHolly.mp4, Em18_Fala1_Neutra_CarolinaHolly\video\Em18_Fala1_Neutra_CarolinaHolly.mp4
mkdir Em18_Fala2_CarolinaHolly, Em18_Fala2_CarolinaHolly\images, Em18_Fala2_CarolinaHolly\audio, Em18_Fala2_CarolinaHolly\video, Em18_Fala2_CarolinaHolly\keypoints
move Em18_Fala2_CarolinaHolly.mp4, Em18_Fala2_CarolinaHolly\video\Em18_Fala2_CarolinaHolly.mp4
mkdir Em18_Fala2_Neutra_CarolinaHolly, Em18_Fala2_Neutra_CarolinaHolly\images, Em18_Fala2_Neutra_CarolinaHolly\audio, Em18_Fala2_Neutra_CarolinaHolly\video, Em18_Fala2_Neutra_CarolinaHolly\keypoints
move Em18_Fala2_Neutra_CarolinaHolly.mp4, Em18_Fala2_Neutra_CarolinaHolly\video\Em18_Fala2_Neutra_CarolinaHolly.mp4
mkdir Em18_Fala3_CarolinaHolly, Em18_Fala3_CarolinaHolly\images, Em18_Fala3_CarolinaHolly\audio, Em18_Fala3_CarolinaHolly\video, Em18_Fala3_CarolinaHolly\keypoints
move Em18_Fala3_CarolinaHolly.mp4, Em18_Fala3_CarolinaHolly\video\Em18_Fala3_CarolinaHolly.mp4
mkdir Em18_Fala3_Neutra_CarolinaHolly, Em18_Fala3_Neutra_CarolinaHolly\images, Em18_Fala3_Neutra_CarolinaHolly\audio, Em18_Fala3_Neutra_CarolinaHolly\video, Em18_Fala3_Neutra_CarolinaHolly\keypoints
move Em18_Fala3_Neutra_CarolinaHolly.mp4, Em18_Fala3_Neutra_CarolinaHolly\video\Em18_Fala3_Neutra_CarolinaHolly.mp4
mkdir Em19_Fala1_CarolinaHolly, Em19_Fala1_CarolinaHolly\images, Em19_Fala1_CarolinaHolly\audio, Em19_Fala1_CarolinaHolly\video, Em19_Fala1_CarolinaHolly\keypoints
move Em19_Fala1_CarolinaHolly.mp4, Em19_Fala1_CarolinaHolly\video\Em19_Fala1_CarolinaHolly.mp4
mkdir Em19_Fala1_Neutra_CarolinaHolly, Em19_Fala1_Neutra_CarolinaHolly\images, Em19_Fala1_Neutra_CarolinaHolly\audio, Em19_Fala1_Neutra_CarolinaHolly\video, Em19_Fala1_Neutra_CarolinaHolly\keypoints
move Em19_Fala1_Neutra_CarolinaHolly.mp4, Em19_Fala1_Neutra_CarolinaHolly\video\Em19_Fala1_Neutra_CarolinaHolly.mp4
mkdir Em19_Fala2_CarolinaHolly, Em19_Fala2_CarolinaHolly\images, Em19_Fala2_CarolinaHolly\audio, Em19_Fala2_CarolinaHolly\video, Em19_Fala2_CarolinaHolly\keypoints
move Em19_Fala2_CarolinaHolly.mp4, Em19_Fala2_CarolinaHolly\video\Em19_Fala2_CarolinaHolly.mp4
mkdir Em19_Fala2_Neutra_CarolinaHolly, Em19_Fala2_Neutra_CarolinaHolly\images, Em19_Fala2_Neutra_CarolinaHolly\audio, Em19_Fala2_Neutra_CarolinaHolly\video, Em19_Fala2_Neutra_CarolinaHolly\keypoints
move Em19_Fala2_Neutra_CarolinaHolly.mp4, Em19_Fala2_Neutra_CarolinaHolly\video\Em19_Fala2_Neutra_CarolinaHolly.mp4
mkdir Em19_Fala3_CarolinaHolly, Em19_Fala3_CarolinaHolly\images, Em19_Fala3_CarolinaHolly\audio, Em19_Fala3_CarolinaHolly\video, Em19_Fala3_CarolinaHolly\keypoints
move Em19_Fala3_CarolinaHolly.mp4, Em19_Fala3_CarolinaHolly\video\Em19_Fala3_CarolinaHolly.mp4
mkdir Em19_Fala3_Neutra_CarolinaHolly, Em19_Fala3_Neutra_CarolinaHolly\images, Em19_Fala3_Neutra_CarolinaHolly\audio, Em19_Fala3_Neutra_CarolinaHolly\video, Em19_Fala3_Neutra_CarolinaHolly\keypoints
move Em19_Fala3_Neutra_CarolinaHolly.mp4, Em19_Fala3_Neutra_CarolinaHolly\video\Em19_Fala3_Neutra_CarolinaHolly.mp4
mkdir Em1_Fala1_CarolinaHolly, Em1_Fala1_CarolinaHolly\images, Em1_Fala1_CarolinaHolly\audio, Em1_Fala1_CarolinaHolly\video, Em1_Fala1_CarolinaHolly\keypoints
move Em1_Fala1_CarolinaHolly.mp4, Em1_Fala1_CarolinaHolly\video\Em1_Fala1_CarolinaHolly.mp4
mkdir Em1_Fala1_CarolinaHolly, Em1_Fala1_CarolinaHolly\images, Em1_Fala1_CarolinaHolly\audio, Em1_Fala1_CarolinaHolly\video, Em1_Fala1_CarolinaHolly\keypoints
move Em1_Fala1_CarolinaHolly.mp4, Em1_Fala1_CarolinaHolly\video\Em1_Fala1_CarolinaHolly.mp4
mkdir Em1_Fala1_Neutra_CarolinaHolly, Em1_Fala1_Neutra_CarolinaHolly\images, Em1_Fala1_Neutra_CarolinaHolly\audio, Em1_Fala1_Neutra_CarolinaHolly\video, Em1_Fala1_Neutra_CarolinaHolly\keypoints
move Em1_Fala1_Neutra_CarolinaHolly.mp4, Em1_Fala1_Neutra_CarolinaHolly\video\Em1_Fala1_Neutra_CarolinaHolly.mp4
mkdir Em1_Fala2_CarolinaHolly, Em1_Fala2_CarolinaHolly\images, Em1_Fala2_CarolinaHolly\audio, Em1_Fala2_CarolinaHolly\video, Em1_Fala2_CarolinaHolly\keypoints
move Em1_Fala2_CarolinaHolly.mp4, Em1_Fala2_CarolinaHolly\video\Em1_Fala2_CarolinaHolly.mp4
mkdir Em1_Fala2_Neutra_CarolinaHolly, Em1_Fala2_Neutra_CarolinaHolly\images, Em1_Fala2_Neutra_CarolinaHolly\audio, Em1_Fala2_Neutra_CarolinaHolly\video, Em1_Fala2_Neutra_CarolinaHolly\keypoints
move Em1_Fala2_Neutra_CarolinaHolly.mp4, Em1_Fala2_Neutra_CarolinaHolly\video\Em1_Fala2_Neutra_CarolinaHolly.mp4
mkdir Em1_Fala3_CarolinaHolly, Em1_Fala3_CarolinaHolly\images, Em1_Fala3_CarolinaHolly\audio, Em1_Fala3_CarolinaHolly\video, Em1_Fala3_CarolinaHolly\keypoints
move Em1_Fala3_CarolinaHolly.mp4, Em1_Fala3_CarolinaHolly\video\Em1_Fala3_CarolinaHolly.mp4
mkdir Em1_Fala3_Neutra_CarolinaHolly, Em1_Fala3_Neutra_CarolinaHolly\images, Em1_Fala3_Neutra_CarolinaHolly\audio, Em1_Fala3_Neutra_CarolinaHolly\video, Em1_Fala3_Neutra_CarolinaHolly\keypoints
move Em1_Fala3_Neutra_CarolinaHolly.mp4, Em1_Fala3_Neutra_CarolinaHolly\video\Em1_Fala3_Neutra_CarolinaHolly.mp4
mkdir Em20_Fala1_CarolinaHolly, Em20_Fala1_CarolinaHolly\images, Em20_Fala1_CarolinaHolly\audio, Em20_Fala1_CarolinaHolly\video, Em20_Fala1_CarolinaHolly\keypoints
move Em20_Fala1_CarolinaHolly.mp4, Em20_Fala1_CarolinaHolly\video\Em20_Fala1_CarolinaHolly.mp4
mkdir Em20_Fala1_Neutra_CarolinaHolly, Em20_Fala1_Neutra_CarolinaHolly\images, Em20_Fala1_Neutra_CarolinaHolly\audio, Em20_Fala1_Neutra_CarolinaHolly\video, Em20_Fala1_Neutra_CarolinaHolly\keypoints
move Em20_Fala1_Neutra_CarolinaHolly.mp4, Em20_Fala1_Neutra_CarolinaHolly\video\Em20_Fala1_Neutra_CarolinaHolly.mp4
mkdir Em20_Fala2_CarolinaHolly, Em20_Fala2_CarolinaHolly\images, Em20_Fala2_CarolinaHolly\audio, Em20_Fala2_CarolinaHolly\video, Em20_Fala2_CarolinaHolly\keypoints
move Em20_Fala2_CarolinaHolly.mp4, Em20_Fala2_CarolinaHolly\video\Em20_Fala2_CarolinaHolly.mp4
mkdir Em20_Fala2_Neutra_CarolinaHolly, Em20_Fala2_Neutra_CarolinaHolly\images, Em20_Fala2_Neutra_CarolinaHolly\audio, Em20_Fala2_Neutra_CarolinaHolly\video, Em20_Fala2_Neutra_CarolinaHolly\keypoints
move Em20_Fala2_Neutra_CarolinaHolly.mp4, Em20_Fala2_Neutra_CarolinaHolly\video\Em20_Fala2_Neutra_CarolinaHolly.mp4
mkdir Em21_Fala1_CarolinaHolly, Em21_Fala1_CarolinaHolly\images, Em21_Fala1_CarolinaHolly\audio, Em21_Fala1_CarolinaHolly\video, Em21_Fala1_CarolinaHolly\keypoints
move Em21_Fala1_CarolinaHolly.mp4, Em21_Fala1_CarolinaHolly\video\Em21_Fala1_CarolinaHolly.mp4
mkdir Em21_Fala1_Neutra_CarolinaHolly, Em21_Fala1_Neutra_CarolinaHolly\images, Em21_Fala1_Neutra_CarolinaHolly\audio, Em21_Fala1_Neutra_CarolinaHolly\video, Em21_Fala1_Neutra_CarolinaHolly\keypoints
move Em21_Fala1_Neutra_CarolinaHolly.mp4, Em21_Fala1_Neutra_CarolinaHolly\video\Em21_Fala1_Neutra_CarolinaHolly.mp4
mkdir Em21_Fala2_CarolinaHolly, Em21_Fala2_CarolinaHolly\images, Em21_Fala2_CarolinaHolly\audio, Em21_Fala2_CarolinaHolly\video, Em21_Fala2_CarolinaHolly\keypoints
move Em21_Fala2_CarolinaHolly.mp4, Em21_Fala2_CarolinaHolly\video\Em21_Fala2_CarolinaHolly.mp4
mkdir Em21_Fala2_Neutra_CarolinaHolly, Em21_Fala2_Neutra_CarolinaHolly\images, Em21_Fala2_Neutra_CarolinaHolly\audio, Em21_Fala2_Neutra_CarolinaHolly\video, Em21_Fala2_Neutra_CarolinaHolly\keypoints
move Em21_Fala2_Neutra_CarolinaHolly.mp4, Em21_Fala2_Neutra_CarolinaHolly\video\Em21_Fala2_Neutra_CarolinaHolly.mp4
mkdir Em21_Fala3_CarolinaHolly, Em21_Fala3_CarolinaHolly\images, Em21_Fala3_CarolinaHolly\audio, Em21_Fala3_CarolinaHolly\video, Em21_Fala3_CarolinaHolly\keypoints
move Em21_Fala3_CarolinaHolly.mp4, Em21_Fala3_CarolinaHolly\video\Em21_Fala3_CarolinaHolly.mp4
mkdir Em21_Fala3_Neutra_CarolinaHolly, Em21_Fala3_Neutra_CarolinaHolly\images, Em21_Fala3_Neutra_CarolinaHolly\audio, Em21_Fala3_Neutra_CarolinaHolly\video, Em21_Fala3_Neutra_CarolinaHolly\keypoints
move Em21_Fala3_Neutra_CarolinaHolly.mp4, Em21_Fala3_Neutra_CarolinaHolly\video\Em21_Fala3_Neutra_CarolinaHolly.mp4
mkdir Em22_Fala1_CarolinaHolly, Em22_Fala1_CarolinaHolly\images, Em22_Fala1_CarolinaHolly\audio, Em22_Fala1_CarolinaHolly\video, Em22_Fala1_CarolinaHolly\keypoints
move Em22_Fala1_CarolinaHolly.mp4, Em22_Fala1_CarolinaHolly\video\Em22_Fala1_CarolinaHolly.mp4
mkdir Em22_Fala1_Neutra_CarolinaHolly, Em22_Fala1_Neutra_CarolinaHolly\images, Em22_Fala1_Neutra_CarolinaHolly\audio, Em22_Fala1_Neutra_CarolinaHolly\video, Em22_Fala1_Neutra_CarolinaHolly\keypoints
move Em22_Fala1_Neutra_CarolinaHolly.mp4, Em22_Fala1_Neutra_CarolinaHolly\video\Em22_Fala1_Neutra_CarolinaHolly.mp4
mkdir Em22_Fala2_CarolinaHolly, Em22_Fala2_CarolinaHolly\images, Em22_Fala2_CarolinaHolly\audio, Em22_Fala2_CarolinaHolly\video, Em22_Fala2_CarolinaHolly\keypoints
move Em22_Fala2_CarolinaHolly.mp4, Em22_Fala2_CarolinaHolly\video\Em22_Fala2_CarolinaHolly.mp4
mkdir Em22_Fala2_Neutra_CarolinaHolly, Em22_Fala2_Neutra_CarolinaHolly\images, Em22_Fala2_Neutra_CarolinaHolly\audio, Em22_Fala2_Neutra_CarolinaHolly\video, Em22_Fala2_Neutra_CarolinaHolly\keypoints
move Em22_Fala2_Neutra_CarolinaHolly.mp4, Em22_Fala2_Neutra_CarolinaHolly\video\Em22_Fala2_Neutra_CarolinaHolly.mp4
mkdir Em22_Fala3_CarolinaHolly, Em22_Fala3_CarolinaHolly\images, Em22_Fala3_CarolinaHolly\audio, Em22_Fala3_CarolinaHolly\video, Em22_Fala3_CarolinaHolly\keypoints
move Em22_Fala3_CarolinaHolly.mp4, Em22_Fala3_CarolinaHolly\video\Em22_Fala3_CarolinaHolly.mp4
mkdir Em22_Fala3_Neutra_CarolinaHolly, Em22_Fala3_Neutra_CarolinaHolly\images, Em22_Fala3_Neutra_CarolinaHolly\audio, Em22_Fala3_Neutra_CarolinaHolly\video, Em22_Fala3_Neutra_CarolinaHolly\keypoints
move Em22_Fala3_Neutra_CarolinaHolly.mp4, Em22_Fala3_Neutra_CarolinaHolly\video\Em22_Fala3_Neutra_CarolinaHolly.mp4
mkdir Em2_Fala1_CarolinaHolly, Em2_Fala1_CarolinaHolly\images, Em2_Fala1_CarolinaHolly\audio, Em2_Fala1_CarolinaHolly\video, Em2_Fala1_CarolinaHolly\keypoints
move Em2_Fala1_CarolinaHolly.mp4, Em2_Fala1_CarolinaHolly\video\Em2_Fala1_CarolinaHolly.mp4
mkdir Em2_Fala1_Neutra_CarolinaHolly, Em2_Fala1_Neutra_CarolinaHolly\images, Em2_Fala1_Neutra_CarolinaHolly\audio, Em2_Fala1_Neutra_CarolinaHolly\video, Em2_Fala1_Neutra_CarolinaHolly\keypoints
move Em2_Fala1_Neutra_CarolinaHolly.mp4, Em2_Fala1_Neutra_CarolinaHolly\video\Em2_Fala1_Neutra_CarolinaHolly.mp4
mkdir Em2_Fala2_CarolinaHolly, Em2_Fala2_CarolinaHolly\images, Em2_Fala2_CarolinaHolly\audio, Em2_Fala2_CarolinaHolly\video, Em2_Fala2_CarolinaHolly\keypoints
move Em2_Fala2_CarolinaHolly.mp4, Em2_Fala2_CarolinaHolly\video\Em2_Fala2_CarolinaHolly.mp4
mkdir Em2_Fala2_Neutra_CarolinaHolly, Em2_Fala2_Neutra_CarolinaHolly\images, Em2_Fala2_Neutra_CarolinaHolly\audio, Em2_Fala2_Neutra_CarolinaHolly\video, Em2_Fala2_Neutra_CarolinaHolly\keypoints
move Em2_Fala2_Neutra_CarolinaHolly.mp4, Em2_Fala2_Neutra_CarolinaHolly\video\Em2_Fala2_Neutra_CarolinaHolly.mp4
mkdir Em2_Fala3_CarolinaHolly, Em2_Fala3_CarolinaHolly\images, Em2_Fala3_CarolinaHolly\audio, Em2_Fala3_CarolinaHolly\video, Em2_Fala3_CarolinaHolly\keypoints
move Em2_Fala3_CarolinaHolly.mp4, Em2_Fala3_CarolinaHolly\video\Em2_Fala3_CarolinaHolly.mp4
mkdir Em2_Fala3_Neutra_CarolinaHolly, Em2_Fala3_Neutra_CarolinaHolly\images, Em2_Fala3_Neutra_CarolinaHolly\audio, Em2_Fala3_Neutra_CarolinaHolly\video, Em2_Fala3_Neutra_CarolinaHolly\keypoints
move Em2_Fala3_Neutra_CarolinaHolly.mp4, Em2_Fala3_Neutra_CarolinaHolly\video\Em2_Fala3_Neutra_CarolinaHolly.mp4
mkdir Em3_Fala1_CarolinaHolly, Em3_Fala1_CarolinaHolly\images, Em3_Fala1_CarolinaHolly\audio, Em3_Fala1_CarolinaHolly\video, Em3_Fala1_CarolinaHolly\keypoints
move Em3_Fala1_CarolinaHolly.mp4, Em3_Fala1_CarolinaHolly\video\Em3_Fala1_CarolinaHolly.mp4
mkdir Em3_Fala1_Neutra_CarolinaHolly, Em3_Fala1_Neutra_CarolinaHolly\images, Em3_Fala1_Neutra_CarolinaHolly\audio, Em3_Fala1_Neutra_CarolinaHolly\video, Em3_Fala1_Neutra_CarolinaHolly\keypoints
move Em3_Fala1_Neutra_CarolinaHolly.mp4, Em3_Fala1_Neutra_CarolinaHolly\video\Em3_Fala1_Neutra_CarolinaHolly.mp4
mkdir Em3_Fala2_CarolinaHolly, Em3_Fala2_CarolinaHolly\images, Em3_Fala2_CarolinaHolly\audio, Em3_Fala2_CarolinaHolly\video, Em3_Fala2_CarolinaHolly\keypoints
move Em3_Fala2_CarolinaHolly.mp4, Em3_Fala2_CarolinaHolly\video\Em3_Fala2_CarolinaHolly.mp4
mkdir Em3_Fala2_Neutra_CarolinaHolly, Em3_Fala2_Neutra_CarolinaHolly\images, Em3_Fala2_Neutra_CarolinaHolly\audio, Em3_Fala2_Neutra_CarolinaHolly\video, Em3_Fala2_Neutra_CarolinaHolly\keypoints
move Em3_Fala2_Neutra_CarolinaHolly.mp4, Em3_Fala2_Neutra_CarolinaHolly\video\Em3_Fala2_Neutra_CarolinaHolly.mp4
mkdir Em3_Fala3_CarolinaHolly, Em3_Fala3_CarolinaHolly\images, Em3_Fala3_CarolinaHolly\audio, Em3_Fala3_CarolinaHolly\video, Em3_Fala3_CarolinaHolly\keypoints
move Em3_Fala3_CarolinaHolly.mp4, Em3_Fala3_CarolinaHolly\video\Em3_Fala3_CarolinaHolly.mp4
mkdir Em3_Fala3_Neutra_CarolinaHolly, Em3_Fala3_Neutra_CarolinaHolly\images, Em3_Fala3_Neutra_CarolinaHolly\audio, Em3_Fala3_Neutra_CarolinaHolly\video, Em3_Fala3_Neutra_CarolinaHolly\keypoints
move Em3_Fala3_Neutra_CarolinaHolly.mp4, Em3_Fala3_Neutra_CarolinaHolly\video\Em3_Fala3_Neutra_CarolinaHolly.mp4
mkdir Em4_Fala1_CarolinaHolly, Em4_Fala1_CarolinaHolly\images, Em4_Fala1_CarolinaHolly\audio, Em4_Fala1_CarolinaHolly\video, Em4_Fala1_CarolinaHolly\keypoints
move Em4_Fala1_CarolinaHolly.mp4, Em4_Fala1_CarolinaHolly\video\Em4_Fala1_CarolinaHolly.mp4
mkdir Em4_Fala1_Neutra_CarolinaHolly, Em4_Fala1_Neutra_CarolinaHolly\images, Em4_Fala1_Neutra_CarolinaHolly\audio, Em4_Fala1_Neutra_CarolinaHolly\video, Em4_Fala1_Neutra_CarolinaHolly\keypoints
move Em4_Fala1_Neutra_CarolinaHolly.mp4, Em4_Fala1_Neutra_CarolinaHolly\video\Em4_Fala1_Neutra_CarolinaHolly.mp4
mkdir Em4_Fala2_CarolinaHolly, Em4_Fala2_CarolinaHolly\images, Em4_Fala2_CarolinaHolly\audio, Em4_Fala2_CarolinaHolly\video, Em4_Fala2_CarolinaHolly\keypoints
move Em4_Fala2_CarolinaHolly.mp4, Em4_Fala2_CarolinaHolly\video\Em4_Fala2_CarolinaHolly.mp4
mkdir Em4_Fala2_Neutra_CarolinaHolly, Em4_Fala2_Neutra_CarolinaHolly\images, Em4_Fala2_Neutra_CarolinaHolly\audio, Em4_Fala2_Neutra_CarolinaHolly\video, Em4_Fala2_Neutra_CarolinaHolly\keypoints
move Em4_Fala2_Neutra_CarolinaHolly.mp4, Em4_Fala2_Neutra_CarolinaHolly\video\Em4_Fala2_Neutra_CarolinaHolly.mp4
mkdir Em4_Fala3_CarolinaHolly, Em4_Fala3_CarolinaHolly\images, Em4_Fala3_CarolinaHolly\audio, Em4_Fala3_CarolinaHolly\video, Em4_Fala3_CarolinaHolly\keypoints
move Em4_Fala3_CarolinaHolly.mp4, Em4_Fala3_CarolinaHolly\video\Em4_Fala3_CarolinaHolly.mp4
mkdir Em4_Fala3_Neutra_CarolinaHolly, Em4_Fala3_Neutra_CarolinaHolly\images, Em4_Fala3_Neutra_CarolinaHolly\audio, Em4_Fala3_Neutra_CarolinaHolly\video, Em4_Fala3_Neutra_CarolinaHolly\keypoints
move Em4_Fala3_Neutra_CarolinaHolly.mp4, Em4_Fala3_Neutra_CarolinaHolly\video\Em4_Fala3_Neutra_CarolinaHolly.mp4
mkdir Em5_Fala1_CarolinaHolly, Em5_Fala1_CarolinaHolly\images, Em5_Fala1_CarolinaHolly\audio, Em5_Fala1_CarolinaHolly\video, Em5_Fala1_CarolinaHolly\keypoints
move Em5_Fala1_CarolinaHolly.mp4, Em5_Fala1_CarolinaHolly\video\Em5_Fala1_CarolinaHolly.mp4
mkdir Em5_Fala1_Neutra_CarolinaHolly, Em5_Fala1_Neutra_CarolinaHolly\images, Em5_Fala1_Neutra_CarolinaHolly\audio, Em5_Fala1_Neutra_CarolinaHolly\video, Em5_Fala1_Neutra_CarolinaHolly\keypoints
move Em5_Fala1_Neutra_CarolinaHolly.mp4, Em5_Fala1_Neutra_CarolinaHolly\video\Em5_Fala1_Neutra_CarolinaHolly.mp4
mkdir Em5_Fala2_CarolinaHolly, Em5_Fala2_CarolinaHolly\images, Em5_Fala2_CarolinaHolly\audio, Em5_Fala2_CarolinaHolly\video, Em5_Fala2_CarolinaHolly\keypoints
move Em5_Fala2_CarolinaHolly.mp4, Em5_Fala2_CarolinaHolly\video\Em5_Fala2_CarolinaHolly.mp4
mkdir Em5_Fala2_Neutra_CarolinaHolly, Em5_Fala2_Neutra_CarolinaHolly\images, Em5_Fala2_Neutra_CarolinaHolly\audio, Em5_Fala2_Neutra_CarolinaHolly\video, Em5_Fala2_Neutra_CarolinaHolly\keypoints
move Em5_Fala2_Neutra_CarolinaHolly.mp4, Em5_Fala2_Neutra_CarolinaHolly\video\Em5_Fala2_Neutra_CarolinaHolly.mp4
mkdir Em5_Fala3_CarolinaHolly, Em5_Fala3_CarolinaHolly\images, Em5_Fala3_CarolinaHolly\audio, Em5_Fala3_CarolinaHolly\video, Em5_Fala3_CarolinaHolly\keypoints
move Em5_Fala3_CarolinaHolly.mp4, Em5_Fala3_CarolinaHolly\video\Em5_Fala3_CarolinaHolly.mp4
mkdir Em5_Fala3_Neutra_CarolinaHolly, Em5_Fala3_Neutra_CarolinaHolly\images, Em5_Fala3_Neutra_CarolinaHolly\audio, Em5_Fala3_Neutra_CarolinaHolly\video, Em5_Fala3_Neutra_CarolinaHolly\keypoints
move Em5_Fala3_Neutra_CarolinaHolly.mp4, Em5_Fala3_Neutra_CarolinaHolly\video\Em5_Fala3_Neutra_CarolinaHolly.mp4
mkdir Em6_Fala1_CarolinaHolly, Em6_Fala1_CarolinaHolly\images, Em6_Fala1_CarolinaHolly\audio, Em6_Fala1_CarolinaHolly\video, Em6_Fala1_CarolinaHolly\keypoints
move Em6_Fala1_CarolinaHolly.mp4, Em6_Fala1_CarolinaHolly\video\Em6_Fala1_CarolinaHolly.mp4
mkdir Em6_Fala1_Neutra_CarolinaHolly, Em6_Fala1_Neutra_CarolinaHolly\images, Em6_Fala1_Neutra_CarolinaHolly\audio, Em6_Fala1_Neutra_CarolinaHolly\video, Em6_Fala1_Neutra_CarolinaHolly\keypoints
move Em6_Fala1_Neutra_CarolinaHolly.mp4, Em6_Fala1_Neutra_CarolinaHolly\video\Em6_Fala1_Neutra_CarolinaHolly.mp4
mkdir Em6_Fala2_CarolinaHolly, Em6_Fala2_CarolinaHolly\images, Em6_Fala2_CarolinaHolly\audio, Em6_Fala2_CarolinaHolly\video, Em6_Fala2_CarolinaHolly\keypoints
move Em6_Fala2_CarolinaHolly.mp4, Em6_Fala2_CarolinaHolly\video\Em6_Fala2_CarolinaHolly.mp4
mkdir Em6_Fala2_Neutra_CarolinaHolly, Em6_Fala2_Neutra_CarolinaHolly\images, Em6_Fala2_Neutra_CarolinaHolly\audio, Em6_Fala2_Neutra_CarolinaHolly\video, Em6_Fala2_Neutra_CarolinaHolly\keypoints
move Em6_Fala2_Neutra_CarolinaHolly.mp4, Em6_Fala2_Neutra_CarolinaHolly\video\Em6_Fala2_Neutra_CarolinaHolly.mp4
mkdir Em7_Fala1_CarolinaHolly, Em7_Fala1_CarolinaHolly\images, Em7_Fala1_CarolinaHolly\audio, Em7_Fala1_CarolinaHolly\video, Em7_Fala1_CarolinaHolly\keypoints
move Em7_Fala1_CarolinaHolly.mp4, Em7_Fala1_CarolinaHolly\video\Em7_Fala1_CarolinaHolly.mp4
mkdir Em7_Fala1_Neutra_CarolinaHolly, Em7_Fala1_Neutra_CarolinaHolly\images, Em7_Fala1_Neutra_CarolinaHolly\audio, Em7_Fala1_Neutra_CarolinaHolly\video, Em7_Fala1_Neutra_CarolinaHolly\keypoints
move Em7_Fala1_Neutra_CarolinaHolly.mp4, Em7_Fala1_Neutra_CarolinaHolly\video\Em7_Fala1_Neutra_CarolinaHolly.mp4
mkdir Em7_Fala2_CarolinaHolly, Em7_Fala2_CarolinaHolly\images, Em7_Fala2_CarolinaHolly\audio, Em7_Fala2_CarolinaHolly\video, Em7_Fala2_CarolinaHolly\keypoints
move Em7_Fala2_CarolinaHolly.mp4, Em7_Fala2_CarolinaHolly\video\Em7_Fala2_CarolinaHolly.mp4
mkdir Em7_Fala2_Neutra_CarolinaHolly, Em7_Fala2_Neutra_CarolinaHolly\images, Em7_Fala2_Neutra_CarolinaHolly\audio, Em7_Fala2_Neutra_CarolinaHolly\video, Em7_Fala2_Neutra_CarolinaHolly\keypoints
move Em7_Fala2_Neutra_CarolinaHolly.mp4, Em7_Fala2_Neutra_CarolinaHolly\video\Em7_Fala2_Neutra_CarolinaHolly.mp4
mkdir Em8_Fala1_CarolinaHolly, Em8_Fala1_CarolinaHolly\images, Em8_Fala1_CarolinaHolly\audio, Em8_Fala1_CarolinaHolly\video, Em8_Fala1_CarolinaHolly\keypoints
move Em8_Fala1_CarolinaHolly.mp4, Em8_Fala1_CarolinaHolly\video\Em8_Fala1_CarolinaHolly.mp4
mkdir Em8_Fala1_Neutra_CarolinaHolly, Em8_Fala1_Neutra_CarolinaHolly\images, Em8_Fala1_Neutra_CarolinaHolly\audio, Em8_Fala1_Neutra_CarolinaHolly\video, Em8_Fala1_Neutra_CarolinaHolly\keypoints
move Em8_Fala1_Neutra_CarolinaHolly.mp4, Em8_Fala1_Neutra_CarolinaHolly\video\Em8_Fala1_Neutra_CarolinaHolly.mp4
mkdir Em8_Fala2_CarolinaHolly, Em8_Fala2_CarolinaHolly\images, Em8_Fala2_CarolinaHolly\audio, Em8_Fala2_CarolinaHolly\video, Em8_Fala2_CarolinaHolly\keypoints
move Em8_Fala2_CarolinaHolly.mp4, Em8_Fala2_CarolinaHolly\video\Em8_Fala2_CarolinaHolly.mp4
mkdir Em8_Fala2_Neutra_CarolinaHolly, Em8_Fala2_Neutra_CarolinaHolly\images, Em8_Fala2_Neutra_CarolinaHolly\audio, Em8_Fala2_Neutra_CarolinaHolly\video, Em8_Fala2_Neutra_CarolinaHolly\keypoints
move Em8_Fala2_Neutra_CarolinaHolly.mp4, Em8_Fala2_Neutra_CarolinaHolly\video\Em8_Fala2_Neutra_CarolinaHolly.mp4
mkdir Em9_Fala1_CarolinaHolly, Em9_Fala1_CarolinaHolly\images, Em9_Fala1_CarolinaHolly\audio, Em9_Fala1_CarolinaHolly\video, Em9_Fala1_CarolinaHolly\keypoints
move Em9_Fala1_CarolinaHolly.mp4, Em9_Fala1_CarolinaHolly\video\Em9_Fala1_CarolinaHolly.mp4
mkdir Em9_Fala1_Neutra_CarolinaHolly, Em9_Fala1_Neutra_CarolinaHolly\images, Em9_Fala1_Neutra_CarolinaHolly\audio, Em9_Fala1_Neutra_CarolinaHolly\video, Em9_Fala1_Neutra_CarolinaHolly\keypoints
move Em9_Fala1_Neutra_CarolinaHolly.mp4, Em9_Fala1_Neutra_CarolinaHolly\video\Em9_Fala1_Neutra_CarolinaHolly.mp4
mkdir Em9_Fala2_CarolinaHolly, Em9_Fala2_CarolinaHolly\images, Em9_Fala2_CarolinaHolly\audio, Em9_Fala2_CarolinaHolly\video, Em9_Fala2_CarolinaHolly\keypoints
move Em9_Fala2_CarolinaHolly.mp4, Em9_Fala2_CarolinaHolly\video\Em9_Fala2_CarolinaHolly.mp4
mkdir Em9_Fala2_Neutra_CarolinaHolly, Em9_Fala2_Neutra_CarolinaHolly\images, Em9_Fala2_Neutra_CarolinaHolly\audio, Em9_Fala2_Neutra_CarolinaHolly\video, Em9_Fala2_Neutra_CarolinaHolly\keypoints
move Em9_Fala2_Neutra_CarolinaHolly.mp4, Em9_Fala2_Neutra_CarolinaHolly\video\Em9_Fala2_Neutra_CarolinaHolly.mp4
mkdir Em9_Fala3_CarolinaHolly, Em9_Fala3_CarolinaHolly\images, Em9_Fala3_CarolinaHolly\audio, Em9_Fala3_CarolinaHolly\video, Em9_Fala3_CarolinaHolly\keypoints
move Em9_Fala3_CarolinaHolly.mp4, Em9_Fala3_CarolinaHolly\video\Em9_Fala3_CarolinaHolly.mp4
mkdir Em9_Fala3_Neutra_CarolinaHolly, Em9_Fala3_Neutra_CarolinaHolly\images, Em9_Fala3_Neutra_CarolinaHolly\audio, Em9_Fala3_Neutra_CarolinaHolly\video, Em9_Fala3_Neutra_CarolinaHolly\keypoints
move Em9_Fala3_Neutra_CarolinaHolly.mp4, Em9_Fala3_Neutra_CarolinaHolly\video\Em9_Fala3_Neutra_CarolinaHolly.mp4